name: Docker Image CI

on:
  push:
    paths:
    - '.github/workflows/docker-image.yml'
    - 'debian-slim/Dockerfile'

jobs:
  debian-slim:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=unixtime::$(date +'%s')"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.job }}
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.job }}/rx-elf-gcc:lateset
          ghcr.io/${{ github.repository_owner }}/${{ github.job }}/rx-elf-gcc:${{ steps.date.outputs.unixtime }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
